version: "3.9"

services:
  web:
    build: ./backend
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=changeme
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
      - redis

  db:
    image: postgis/postgis:15-3.3
    container_name: postgres_postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_broker
    ports:
      - "6379:6379"

  worker:
    build: ./backend
    command: celery -A core worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db

  beat:
    build: ./backend
    command: celery -A core beat -l info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db

volumes:
  pgdata:
